config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  root "pages#home"
  get "pages/about", to: "pages#about"
  resources :articles # , only: [:show, :index, :new, :create]
  get "signup", to: "users#new"
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except:[:destroy]
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories,through: :article_categories
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 5000}
  validates :category_ids, presence:true
end

app/models/article_category.rb
class ArticleCategory <ApplicationRecord
  belongs_to:article
  belongs_to:category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence:true, length:{minimum:3, maximum:25}
  validates_uniqueness_of :name 

  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles,dependent: :destroy
  validates :username, presence: true, 
             uniqueness: {case_sensitive: false},
             length: {minimum: 3, maximum: 25}
             
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


  validates :email, presence: true,
             uniqueness: {case_sensitive: false},
             length: {maximum: 105},
             format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  def current_user 
    @current_user ||= User.find(session[:user_id])if session[:user_id]
  end
  def logged_in?
    !!current_user
  end
 
  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except:[:show,:index]
  before_action :require_same_user, only:[:edit, :update, :destroy]

  def show
    # @article = Article.find(params[:id])
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)
    # @article.user = User.find(session[:user_id])
    @article.user = current_user
    if @article.save
      flash[:notice] = "Article was created successfully."
      # redirect_to article_path(@article)
      redirect_to @article
    else
      render :new
    end
  end

  def update
    # @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully."
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, notice: "Article was successfully deleted."
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids:[])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own article"
      redirect_to @article
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController <ApplicationController
  
  before_action :require_admin, except: [:index, :show]
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice]="Category was successfully created"
      redirect_to @category
    else
      render 'new'
    end
  end
  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Your category has been updated successfully."
      redirect_to @category
    else
      render "edit"
    end
  end
  def index
   @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
private 
def category_params
  params.require(:category).permit(:name)
end
def require_admin
  if !(logged_in? && current_user.admin?)
    flash[:alert]="Only admin can perform that action"
    redirect_to categories_path
  end
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
     if logged_in?
       redirect_to articles_path
     end
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
   def new
   end

   def create
    user =User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id]=user.id
      flash[:notice]="Logged in successfully"
      redirect_to user
    else
        flash.now[:alert]="Oops! Your login credentials don't seem to match. Please try again."
        render 'new'  
    end
   end

   def destroy
    session[:user_id]=nil
    # @current_user = nil 
    flash[:notice]="Logged out"
    redirect_to  root_path
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update,:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id]= @user.id
      flash[:notice] = "Hello #{@user[:username]} , Welcome to Alpha Blog."
      redirect_to @user
    else
      render "new"
    end
  end
  def edit
    # @user = User.find(params[:id])
  end
  def update
    # @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account has been updated successfully."
      redirect_to @user
    else
      render "edit"
    end
  end
  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end
  def index 
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def destroy
    if current_user.admin?
      @user.destroy
      flash[:notice] ="Account and all associated articles successfully deleted"
      redirect_to user_path
    else
      @user.destroy
      session[:user_id]= nil if @user == current_user
      flash[:notice] ="Account and all associated articles successfully deleted"
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit your own account."
      redirect_to @user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(type)
    case type.to_sym
    when :notice then "alert-success"  # Green for success messages
    when :alert then "alert-danger"    # Red for error messages
    else "alert-info"                  # Default (Blue)
    end
  end

  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]   
    image_src = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(image_src, alt: user.username, class: "rounded shadow mx-auto d-block")
  end
  # def current_user 
  #   @current_user ||= User.find(session[:user_id])if session[:user_id]
  # end

  # def logged_in?
  #   !!current_user
  # end
  

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<% @articles.each do |article| %>
  <div class="row justify-content-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow  mb-5 bg-body-tertiary rounded">
        <div class="card-header fst-italic ">
          <% if article.user%>
            Created by @<%= link_to article.user.username, user_path(article.user),class:"text-decoration-none" %>
          <% end %>
          <% if article.categories.any?%>
            <div class="mt-2">
              <%= render article.categories%>
            </div>
          <% end%>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to article.title, article_path(article), class: "text-success text-decoration-none " %>
          </h5>
          <p class="card-text"><%= truncate(article.description,length:50)  %></p>
          <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
          <%= link_to 'Show', article_path(article),class:"btn btn-outline-success" %>
          <% if logged_in? && (article.user==current_user || current_user.admin?)%>
            <%= link_to 'Edit', edit_article_path(article) ,class:"btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article),data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },class:"btn btn-outline-danger" %>
          <% end %>
        </div>
        <div class="card-footer text-body-secondary">
          <small>Created <%= time_ago_in_words(article.created_at)%> ago
            , edited ago <%=time_ago_in_words(article.updated_at)%> ago </small>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="container ">
  <div class="row justify-content-center ">
    <div class="col-8 " >
      <%= render 'shared/errors', obj:@article%>
      <%= form_with model: @article, local: true, class:"shadow p-2 mb-3 rounded formbg", data: { turbo: false } do |f| %>
        <div class="from-group row ">
          <%= f.label :title , class:"col-sm-2 col-form-label fw-semibold "%>
          <div class= "col-sm-10">
            <%= f.text_field :title ,class:"form-control shadow rounded ",placeholder:"Title of article" %>
          </div>
        </div>
        <div class="from-group row mt-4">
          <%= f.label :description,  class:"col-sm-2 col-form-label fw-semibold "%>
          <div class= "col-sm-10">
            <%= f.text_area :description, rows:10, class:"form-control shadow rounded ",placeholder:"Description of article" %>
          </div>
        </div>
        <div class="from-group row mt-4">
          <%= f.label :category_ids, "Categories", class: "col-sm-2 col-form-label fw-semibold" %>
          <div class="col-sm-10">
            <%= f.collection_select :category_ids, Category.all, :id, :name, 
             { prompt: "Make your selection from the list below(can't be empty)" }, 
             { multiple: true, size:3, class: "form-control shadow rounded " }
              %>
          </div>
        </div>
        <div class="form-group row mt-2 justify-content-center">
          <%= f.submit "Save Article  ", class: "btn btn-outline-info w-auto text-light fw-semibold " %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to 'Back', articles_path(@article), class: "btn btn-outline-primary btn-sm mb-5 rounded" %>
    </div>
  </div>

app/views/articles/edit.html.erb
<h1  class="text-center mt-4 fw-semibold">Edit Article </h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4 fw-semibold " >Listing all articles</h1>
<%# <%= will_paginate @article %>
<div class="flickr_pagination">
  <%= will_paginate @Articles, :container => false %>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @Articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1  class="text-center mt-4 fw-semibold">Create new Article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row justify-content-center">
  <div class="col-8 mt-4">
    <div class="card shadow mb-5 bg-body-tertiary rounded">
      <div class="card-header fst-italic text-center">
        Created by @<%= @article.user.username if @article.user %>
        <%= link_to gravatar_for(@article.user),user_path(@article.user)%>
        <% if @article.categories.any?%>
          <div class="mt-2">
            <%= render @article.categories%>
          </div>
        <% end%>
      </div>
      <div class="card-body">
        <h5 class="card-title text-center">
          <%= link_to @article.title, article_path(@article), class: "text-success text-decoration-none" %>
        </h5>
        <div class="card-text text-start"><%= simple_format(@article.description) %></div>
        <div class="text-center">
          <% if logged_in? && (@article.user==current_user || current_user.admin?)%>
            <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-outline-info btn-sm" %>
            <%= link_to "Delete", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm mx-2" %>
          <% end %>
          <%= link_to 'Back', articles_path(@article), class: "btn btn-outline-primary rounded" %>
        </div>
      </div>
      <div class="card-footer text-body-secondary text-center">
        <small>Created <%= time_ago_in_words(@article.created_at) %> ago, edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge rounded-pill text-bg-secondary text-decoration-none mr-1" %>

app/views/categories/edit.html.erb
<h1  class="text-center mt-4 fw-semibold">Edit a category</h1>
<div class="container ">
  <div class="row justify-content-center ">
    <div class="col-8 " >
      <%= render 'shared/errors',obj: @category %>
      <%= form_with model: @category, local: true, class:"shadow p-2 mb-3 rounded formbg", data: { turbo: false } do |f| %>
        <div class="form-group row mt-3">
          <%= f.label @category.name, class:"col-sm-3 col-form-label fw-semibold "%>
          <div class= "col-sm-9">
            <%= f.text_field :name ,class:"form-control shadow rounded ",placeholder:"Enter a name" %>
          </div>
        </div>
        <div class="form-group row mt-4 mb-2 justify-content-center">
          <%= f.submit class: "btn btn-outline-info w-auto text-light fw-semibold" %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to 'Back',  categories_path, class: "btn btn-outline-primary btn-sm mb-5 rounded" %>
    </div>
  </div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4 fw-semibold ">Categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<% @categories.each do |category| %>
  <div class="row justify-content-center ">
    <div class="col-4 mt-4">
      <div class="card text-center shadow  mb-5 bg-body-tertiary rounded">
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to category.name, category_path(category), class: "text-success text-decoration-none " %>
          </h5>
          <p class="card-text"><%= pluralize(category.articles.count,"article") %></p>
        </div>
        <div class="card-footer text-body-secondary">
          <small>Created <%= time_ago_in_words(category.created_at)%> ago
            , edited ago <%=time_ago_in_words(category.updated_at)%> ago </small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1  class="text-center mt-4 fw-semibold">Create a new category</h1>
<div class="container ">
  <div class="row justify-content-center ">
    <div class="col-8 " >
      <%= render 'shared/errors',obj: @category %>
      <%= form_with model: @category, local: true, class:"shadow p-2 mb-3 rounded formbg", data: { turbo: false } do |f| %>
        <div class="form-group row mt-3">
          <%= f.label :name,"Category name", class:"col-sm-3 col-form-label fw-semibold "%>
          <div class= "col-sm-9">
            <%= f.text_field :name ,class:"form-control shadow rounded ",placeholder:"Enter a name" %>
          </div>
        </div>
        <div class="form-group row mt-4 mb-2 justify-content-center">
          <%= f.submit class: "btn btn-outline-info w-auto text-light fw-semibold" %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to 'Back',  categories_path, class: "btn btn-outline-primary btn-sm mb-5 rounded" %>
    </div>
  </div>

app/views/categories/show.html.erb
<h1  class="text-center mt-4 fw-semibold">Category : <%= @category.name %> </h1>
<div class="text-center mt-4">
  <% if logged_in? && current_user.admin?%>
    <%= link_to 'Edit category', edit_category_path(@category) ,class:"btn btn-outline-info " %>
  <% end%>
</div>
<div class="flickr_pagination">
  <%= will_paginate @articles,:container => false %>
</div>
<%= render 'articles/article'%>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer text-white text-center py-2 fixed-bottom fst-italic">
  Copyright &copy; 2025 Alpha Blog @pravin
</footer>

app/views/layouts/_message.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert <%= flash_class(name) %> text-center alert-dismissible fade show">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%# <a class="navbar-brand" id="logo" href="#">Alpha Blog</a> %>
    <%= link_to "Alpha Blog",root_path, class:"navbar-brand",id:"logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <li> <%= link_to "New Article",new_article_path , class:"dropdown-item " %></li>
            <% end%>
            <li> <%= link_to "All Articles", articles_path , class:"dropdown-item " %></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin?  %>
              <li> <%= link_to "New Category",new_category_path , class:"dropdown-item " %></li>
            <% end%>
            <li> <%= link_to "All Categories", categories_path , class:"dropdown-item " %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers",users_path,class:"nav-link"%>
        </li>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%="(Admin)" if current_user.admin? %>Profile [<%= truncate(current_user.username,length:10)%>]
            </a>
            <ul class="dropdown-menu">
              <li> <%= link_to "View your profile",user_path(current_user) , class:"dropdown-item " %></li>
              <li> <%= link_to "Edit your profile", edit_user_path(current_user) , class:"dropdown-item " %></li>
              <li> <%= link_to "Delete profile", user_path(current_user) , class:"dropdown-item text-danger " ,
              data: { turbo_method: :delete, turbo_confirm: "Are you sure want to delete the user account and add associated article?" }%></li>
            </ul>
          </li>
          <li class="nav-item">
            <%= link_to "Logout", logout_path, class: "nav-link", data: { turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login",login_path,class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up",signup_path,class:"nav-link"%>
          </li>
        <% end %>
        <%# <li class="nav-item">
          <a class="nav-link" href="#">Connect Us!</a>
        </li> %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- ✅ Keep only this for Importmap -->
    <%= javascript_importmap_tags %>
    <%# <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <script>
      console.log("JavaScript is running!");
    </script>
  </head>
  <body>
    <%= render 'layouts/navigation'%>
    <div class="container">
      <%= render 'layouts/message'%>
      <%= yield %>
    </div>
    <%= render'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<h1>hi</h1>

app/views/pages/home.html.erb
<div class="container mt-4">
  <div class="p-5 mb-4  home-img rounded-3 text-center">
    <div class="container-fluid py-5">
      <h1 class="display-5 fw-bold ">Alpha Blog </h1>
      <p class="quote" >
        Your thoughts, your words, your story...shared with the world!
      </p>
      <%= link_to "Sign Up!", signup_path, class: "btn btn-outline-info btn-lg" %>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
 <% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <strong>Oops! We encountered some errors</strong>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li class="text-warning-emphasis">
          <%= msg %>
        </li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container ">
  <div class="row justify-content-center ">
    <div class="col-8 " >
      <%= render 'shared/errors',obj: @user %>
      <%= form_with model: @user, local: true, class:"shadow p-2 mb-3 rounded formbg", data: { turbo: false } do |f| %>
        <div class="form-group row mt-3">
          <%= f.label :username , class:"col-sm-2 col-form-label fw-semibold "%>
          <div class= "col-sm-10">
            <%= f.text_field :username ,class:"form-control shadow rounded ",placeholder:"Enter a username" %>
          </div>
        </div>
        <div class="form-group row mt-4">
          <%= f.label :email, class: "col-sm-2 col-form-label fw-semibold" %>
          <div class="col-sm-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>
        <div class="form-group row mt-4">
          <%= f.label :password,  class:"col-sm-2 col-form-label fw-semibold "%>
          <div class= "col-sm-10">
            <%= f.password_field :password, class:"form-control shadow rounded ",placeholder:"Enter a password" %>
          </div>
        </div>
        <div class="form-group row mt-4 mb-2 justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-info w-auto text-light fw-semibold") %>
        </div>
      <% end %>
    </div>
    <div class="d-flex justify-content-center">
      <%= link_to 'Back', logged_in? ? user_path(current_user) : root_path, class: "btn btn-outline-primary btn-sm mb-5 rounded" %>
    </div>
  </div>

app/views/users/edit.html.erb
<h1  class="text-center mt-4 fw-semibold">Edit your profile </h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1  class="text-center mt-4 fw-semibold">Alpha Bloggers</h1>
<div class="flickr_pagination">
  <%= will_paginate @Articles, :container => false %>
</div>
<% @users.each do |user| %>
  <div class="row justify-content-center ">
    <div class="col-8 mt-4">
      <div class="card text-center shadow  mb-5 bg-body-tertiary rounded">
        <div class="card-header fst-italic ">
          <%= link_to user.username,user,class:"text-decoration-none" %>
        </div>
        <div class="card-body">
          <h5 class="card-title">
            <%= link_to gravatar_for(user,size:150),user, class: "text-success text-decoration-none " %>
          </h5>
          <p class="card-text"><%= pluralize(user.articles.count,"article") %></p>
          <%= link_to 'View profile', user,class:"btn btn-outline-success" %>
          <% if logged_in? %>
            <% if user == current_user%>
              <%= link_to 'Edit profile', edit_user_path(user) ,class:"btn btn-outline-info" %>
            <% end%>
            <% if current_user.admin?%>
              <%= link_to "Delete user", user_path(user) , class:"btn btn-outline-danger" ,data: { turbo_method: :delete, turbo_confirm: "Are you sure want to delete the user account and add associated article?" }%>
            <% end%>
          <%end%>
        </div>
        <div class="card-footer text-body-secondary">
          <small>Joined <%= time_ago_in_words(user.created_at)%> ago </small>
        </div>
      </div>
    </div>
  </div>
<% end %>
<div class="flickr_pagination mb-4">
  <%= will_paginate @Articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1  class="text-center mt-4 fw-semibold">Sign Up!</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1  class="text-center mt-4 fw-semibold"><%= @user.username %>'s profile </h1>
<%= gravatar_for @user,size: 150 %>
<% if logged_in? && @user == current_user%>
  <div class="text-center mt-4">
    <%= link_to "Edit your profile",edit_user_path(@user), class:"btn btn-outline-info" %>
  </div>
<% end %>
<h3  class="text-center mt-4 fw-semibold">Articles</h3>
<div class="flickr_pagination">
  <%= will_paginate @articles,:container => false %>
</div>
<%= render 'articles/article'%>
<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>